<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $isDbMapping
 * @var \Mapper\Api\Representation\MapperRepresentation|null $mapping
 * @var \Mapper\Api\Representation\MapperRepresentation|null $resource
 * @var string $label
 * @var string $content
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/mapper.css', 'Mapper'));
$this->headScript()
    ->appendFile($assetUrl('js/codemirror-mapper.js', 'Mapper'));

$this->htmlElement('body')->appendAttribute('class', 'mapper show');
?>

<?= $this->pageTitle($translate('Show mapping'), 1, $translate('Mapper')) ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed(\Mapper\Api\Adapter\MapperAdapter::class, 'create')): ?>
    <?php if (is_object($mapping) && $mapping->userIsAllowed('update')): ?>
    <?= $hyperlink($translate('Edit'), $url(null, ['action' => 'edit'], true), ['class' => 'button']) ?>
    <?php endif; ?>
    <?= $hyperlink($translate('Copy'), $url(null, ['action' => 'copy'], ['query' => $this->params()->fromQuery()], true), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<div id="mapper">
    <h2 class="label"><?= $escape($label) ?></h2>
    <textarea id="o-mapper-mapping" class="mapping-content"><?= $escape($content) ?></textarea>
</div>
